#!/bin/env python

import subprocess
import json
import sys
import time
from itertools import chain


def tree():
    return json.loads(subprocess.check_output(["swaymsg", "-t", "get_tree"]))


def loop(msg):
    if msg["change"] == "new":
        width = msg["container"]["rect"]["width"]
        height = msg["container"]["rect"]["height"]

        nodes = tree()["nodes"]
        output_nodes = filter(lambda x: x["type"] == "output", nodes)

        print(width, height)
        
        if width >= height:
            subprocess.run(["swaymsg", "splitv"])
        else:
            subprocess.run(["swaymsg", "splith"])



def main():
    process = subprocess.Popen(
        ["swaymsg", "-m", "-r", "-t", "subscribe", '["window"]'], stdout=subprocess.PIPE
    )

    while True:
        try:
            msg = json.loads(process.stdout.readline())
            loop(msg)
        except Exception as e:
            raise e
            print(e)


if __name__ == "__main__":
    main()
