#!/bin/env python

import subprocess
import json
import sys
import time


def loop(msg):
    width = msg["container"]["rect"]["width"]
    height = msg["container"]["rect"]["height"]

    if msg["change"] == "focus":
        if width >= height:
            subprocess.run(["swaymsg", "splith"])
        else:
            subprocess.run(["swaymsg", "splitv"])


def main():
    process = subprocess.Popen(["swaymsg", "-m", "-r", "-t", "subscribe", '["window"]'], stdout=subprocess.PIPE)

    while True:
        try:
            msg = json.loads(process.stdout.readline())
            print(json.dumps(msg, indent=4))
            loop(msg)
        except Exception as e:
            print(e)


if __name__ == "__main__":
    main()
