#!/bin/python

import subprocess
import json
import sys

focused = subprocess.run("swaymsg -t get_workspaces | jq -r '.[] | select(.focused==true).output'", shell=True, capture_output=True).stdout.decode("utf8").strip()
scale = float(subprocess.run(f"swaymsg -t get_tree | jq -r '.nodes | .[] | select(.name=\"{focused}\").scale'", shell=True, capture_output=True).stdout.decode("utf8").strip()[5:])

new_scale = round(eval(sys.argv[1].replace("scale", str(scale))) * 100)/100

subprocess.run(f"swaymsg output {focused} scale {new_scale}", shell=True)
