#!/bin/env python

import subprocess

capacity = subprocess.run(
    ["cat", "/sys/class/power_supply/BAT1/capacity"], capture_output=True
)
date = subprocess.run(["date", "+%Y年%m月%d日%I時%M分"], capture_output=True)

print(
    "",
    date.stdout.decode("utf8").strip(),
    " ",
    "󰁹 ",
    capacity.stdout.decode("utf8").strip(),
    sep="",
)
