#!/usr/bin/env bash

pkill kanshi
kanshi &

# Its convienent to have steam contantly running
#if [ -z $(pgrep steam) ]; then
#	echo "Starting Steam"
#	flatpak run com.valvesoftware.Steam -silent &
#fi

# Do the same for discord
if [ -z $(pgrep discord) ]; then
	echo "Starting Discord"
	flatpak run com.discordapp.Discord --start-minimized & 
fi


pkill dunst
dunst &

lxqt-policykit-agent &

flatpak run org.fcitx.Fcitx5 -d &

keyd-application-mapper -d

pkill -f battery-monitor
battery-monitor &

pkill -f bspwm-tile
./bspwm-tile &

pkill -f desktop-thingies
# desktop-thingies -c ~/.config/desktop-thingies/config.py &
desktop-thingies -c ~/.config/desktop-thingies/config2.py &
