#! /bin/sh

~/.screenlayout/tripple.sh
picom --experimental-backends &
nitrogen --restore &
lxqt-policykit-agent &
nm-applet &


#Start polybar
~/.config/polybar/launch.sh
#Get rid of gaps
bspc config top_padding 27
bspc config right_padding 2
bspc config left_padding 2
bspc config bottom_padding 2

#Mouse warping
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4
bspc monitor HDMI-1-1 -d 5 6 7 8
bspc monitor DP-0  -d 9 10 11 12

bspc config border_width         2
bspc config border_radius        0
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#5B6ED9
bspc config normal_border_color \#364959
bspc config active_border_color \#364959
bspc config presel_feedback_color \#364959


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
