#! /bin/fish

#picom --experimental-backends &
#picom &
lxqt-policykit-agent &
# nm-applet &

pkill kmonad
kmonad ~/.config/kmonad/layout.kbd &

pkill picom
pkill dunst

pkill fcitx
fcitx &

pkill -f warn.py
/home/lunar/Documents/Projects/battery-warn/warn.py &

if [ -n "$IS_DESKTOP" ]
    dunst -config "~/.config/dunst/desktoprc" &
    # Set DPI
    ~ ./.screenlayout/desktop.sh
    picom --experimental-backends &
    ~/.config/polybar/launch.sh "/home/lunar/.config/polybar/config2" &
    kmonad ~/.config/kmonad/layout-2.kbd &

    bspc config top_padding 22
    bspc config right_padding 2
    bspc config left_padding 2
    bspc config bottom_padding 2

    bspc monitor HDMI-0 -d 1 2 3 4 5 6
    bspc monitor DP-1-4 -d 7 8 9 10 11 12
    bspc monitor eDP-1 -d 13 14 15 16 17 18

    bspc config border_width         2
    bspc config border_radius        0
    bspc config window_gap           2

    bspc config focused_border_color \#3496f7
    bspc config normal_border_color \#030311
    bspc config active_border_color \#030311
    bspc config presel_feedback_color \#030311
else
    dunst &
    xrandr --dpi 192 || true
    #Start polybar
    ~/.config/polybar/launch.sh "/home/lunar/.config/polybar/config" &
    #Get rid of gaps
    bspc config top_padding 34
    bspc config right_padding 2
    bspc config left_padding 2
    bspc config bottom_padding 2

    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0

    bspc config border_width         3
    bspc config border_radius        0
    bspc config window_gap           3

    bspc config focused_border_color \#AAAAAA
    bspc config normal_border_color \#000000
    bspc config active_border_color \#000000
    bspc config presel_feedback_color \#000000
end

./setup_wallpaper

# libinput
set id (xinput --list | grep "Touchpad" | awk -F[=] '{print $2}' | awk -F[\t] '{print $1}')

xinput --set-prop $id "libinput Natural Scrolling Enabled" 1
xinput --set-prop $id "libinput Tapping Enabled" 1
xinput --set-prop  $id 'libinput Disable While Typing Enabled' 0

#Wallpapers
# ./launch_wallpaper ~/.config/wallpaper/very_lewd.toml
# ./launch_wallpaper

# Scrolling
libinput-gestures-setup start

#Mouse warping
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config focused_border_color \#5B6ED9
#bspc config normal_border_color \#364959
#bspc config active_border_color \#364959
#bspc config presel_feedback_color \#364959

bspc rule -a Game desktop='^8' state=floating follow=on
bspc rule -a XIVLauncher.Core state=floating center
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
